//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupamentos
    {
        public Agrupamentos()
        {
            this.estabelecimentos = new HashSet<estabelecimentos>();
        }
    
        public int Codagrupamento { get; set; }
        public string agrupamento { get; set; }
    
        public virtual ICollection<estabelecimentos> estabelecimentos { get; set; }
    }
}
