//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public string Nick { get; set; }
        public int idmanual { get; set; }
        public System.DateTime DataStamp { get; set; }
        public Nullable<bool> Activa { get; set; }
        public int IdAlerta { get; set; }
    
        public virtual manuais manuais { get; set; }
        public virtual users users { get; set; }
    }
}
