//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPostal
    {
        public CPostal()
        {
            this.estabelecimentos = new HashSet<estabelecimentos>();
            this.users = new HashSet<users>();
        }
    
        public int cp4 { get; set; }
        public int cp3 { get; set; }
        public string Freguesia { get; set; }
        public string Concelho { get; set; }
        public string Distrito { get; set; }
    
        public virtual ICollection<estabelecimentos> estabelecimentos { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
