//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinas
    {
        public Disciplinas()
        {
            this.manuais = new HashSet<manuais>();
            this.mestab = new HashSet<mestab>();
        }
    
        public string disciplina { get; set; }
    
        public virtual ICollection<manuais> manuais { get; set; }
        public virtual ICollection<mestab> mestab { get; set; }
    }
}
