//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estabelecimentos
    {
        public estabelecimentos()
        {
            this.mestab = new HashSet<mestab>();
        }
    
        public int idestab { get; set; }
        public string design { get; set; }
        public string morada { get; set; }
        public string local { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string url { get; set; }
        public Nullable<int> CodAgrupamento { get; set; }
        public Nullable<bool> Sede { get; set; }
        public Nullable<int> cp4 { get; set; }
        public Nullable<int> cp3 { get; set; }
    
        public virtual Agrupamentos Agrupamentos { get; set; }
        public virtual CPostal CPostal { get; set; }
        public virtual ICollection<mestab> mestab { get; set; }
    }
}
