//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manuais
    {
        public manuais()
        {
            this.Alertas = new HashSet<Alertas>();
            this.mestab = new HashSet<mestab>();
            this.stock = new HashSet<stock>();
        }
    
        public int idmanual { get; set; }
        public string Editora { get; set; }
        public string disciplina { get; set; }
        public string ISBN { get; set; }
        public string titulo { get; set; }
        public string Autores { get; set; }
        public string foto { get; set; }
        public Nullable<int> idAEscola { get; set; }
        public Nullable<bool> Inactivo { get; set; }
    
        public virtual ICollection<Alertas> Alertas { get; set; }
        public virtual AnosEscolares AnosEscolares { get; set; }
        public virtual Disciplinas Disciplinas { get; set; }
        public virtual Editoras Editoras { get; set; }
        public virtual ICollection<mestab> mestab { get; set; }
        public virtual ICollection<stock> stock { get; set; }
    }
}
