//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuaisEstabelecimentos
    {
        public int idmanual { get; set; }
        public string isbn { get; set; }
        public string titulo { get; set; }
        public string Editora { get; set; }
        public string disciplina { get; set; }
        public string Autores { get; set; }
        public string foto { get; set; }
        public string Aletivo { get; set; }
        public string estab { get; set; }
        public string Ano { get; set; }
    }
}
