//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuaisEmStock
    {
        public int idmanual { get; set; }
        public string ISBN { get; set; }
        public string titulo { get; set; }
        public string foto { get; set; }
        public string autores { get; set; }
        public string disciplina { get; set; }
        public string editora { get; set; }
        public int idStock { get; set; }
        public string nick { get; set; }
        public int idAEscola { get; set; }
        public string Escalao { get; set; }
        public string ano { get; set; }
    }
}
