//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagens
    {
        public byte[] IdMR { get; set; }
        public string Mensagem { get; set; }
        public string Nickname { get; set; }
        public System.DateTime Data { get; set; }
        public string NickEnviado { get; set; }
        public Nullable<bool> Lido { get; set; }
    
        public virtual users users { get; set; }
    }
}
