//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mestab
    {
        public int idMestab { get; set; }
        public string Aletivo { get; set; }
        public Nullable<int> idmanual { get; set; }
        public Nullable<int> idestab { get; set; }
        public Nullable<int> idaescola { get; set; }
        public string disciplina { get; set; }
    
        public virtual ALetivo ALetivo1 { get; set; }
        public virtual AnosEscolares AnosEscolares { get; set; }
        public virtual Disciplinas Disciplinas { get; set; }
        public virtual estabelecimentos estabelecimentos { get; set; }
        public virtual manuais manuais { get; set; }
    }
}
