//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int idStock { get; set; }
        public Nullable<int> idManual { get; set; }
        public Nullable<int> Qtt { get; set; }
        public string Nick { get; set; }
        public System.DateTime DataStamp { get; set; }
    
        public virtual manuais manuais { get; set; }
        public virtual users users { get; set; }
    }
}
