//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrocamanuaisEntities : DbContext
    {
        public TrocamanuaisEntities()
            : base("name=TrocamanuaisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agrupamentos> Agrupamentos { get; set; }
        public virtual DbSet<Alertas> Alertas { get; set; }
        public virtual DbSet<ALetivo> ALetivo { get; set; }
        public virtual DbSet<AnosEscolares> AnosEscolares { get; set; }
        public virtual DbSet<CPostal> CPostal { get; set; }
        public virtual DbSet<Disciplinas> Disciplinas { get; set; }
        public virtual DbSet<Editoras> Editoras { get; set; }
        public virtual DbSet<Escaloes> Escaloes { get; set; }
        public virtual DbSet<estabelecimentos> estabelecimentos { get; set; }
        public virtual DbSet<manuais> manuais { get; set; }
        public virtual DbSet<Mensagens> Mensagens { get; set; }
        public virtual DbSet<mestab> mestab { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<TodosManuais> TodosManuais { get; set; }
        public virtual DbSet<ManuaisEstabelecimentos> ManuaisEstabelecimentos { get; set; }
        public virtual DbSet<ManuaisEmStock> ManuaisEmStock { get; set; }
    }
}
