//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupamento
    {
        public Agrupamento()
        {
            this.estabelecimentos = new HashSet<estabelecimento>();
        }
    
        public int Codagrupamento { get; set; }
        public string agrupamento1 { get; set; }
    
        public virtual ICollection<estabelecimento> estabelecimentos { get; set; }
    }
}
