//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnosEscolare
    {
        public AnosEscolare()
        {
            this.manuais = new HashSet<manuai>();
            this.mestabs = new HashSet<mestab>();
        }
    
        public string Escalao { get; set; }
        public int idAEscola { get; set; }
        public string Ano { get; set; }
    
        public virtual ICollection<manuai> manuais { get; set; }
        public virtual ICollection<mestab> mestabs { get; set; }
        public virtual Escalo Escalo { get; set; }
    }
}
