//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class mestab
    {
        public int idMestab { get; set; }
        public string Aletivo { get; set; }
        public Nullable<int> idmanual { get; set; }
        public Nullable<int> idestab { get; set; }
        public Nullable<int> idaescola { get; set; }
        public string disciplina { get; set; }
        public string Editora { get; set; }
    
        public virtual ALetivo ALetivo1 { get; set; }
        public virtual AnosEscolare AnosEscolare { get; set; }
        public virtual Disciplina Disciplina1 { get; set; }
        public virtual estabelecimento estabelecimento { get; set; }
        public virtual manuai manuai { get; set; }
    }
}
