//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrocaManuaisEntities : DbContext
    {
        public TrocaManuaisEntities()
            : base("name=TrocaManuaisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agrupamento> Agrupamentos { get; set; }
        public virtual DbSet<ALetivo> ALetivoes { get; set; }
        public virtual DbSet<AnosEscolare> AnosEscolares { get; set; }
        public virtual DbSet<CPostal> CPostals { get; set; }
        public virtual DbSet<Disciplina> Disciplinas { get; set; }
        public virtual DbSet<Editora> Editoras { get; set; }
        public virtual DbSet<Escalo> Escaloes { get; set; }
        public virtual DbSet<estabelecimento> estabelecimentos { get; set; }
        public virtual DbSet<manuai> manuais { get; set; }
        public virtual DbSet<Mensagen> Mensagens { get; set; }
        public virtual DbSet<mestab> mestabs { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
