//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrocaManuais.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Mensagens = new HashSet<Mensagen>();
            this.stocks = new HashSet<stock>();
        }
    
        public string Nick { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string nome { get; set; }
        public Nullable<bool> BLivro { get; set; }
        public Nullable<int> cp4 { get; set; }
        public Nullable<int> cp3 { get; set; }
    
        public virtual CPostal CPostal { get; set; }
        public virtual ICollection<Mensagen> Mensagens { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
    }
}
